Add Monaco editor
pchampin/sowasm pull request #9
Opened 2023-11-29 10:58 UTC by vemonet

Hi @pchampin , about https://github.com/pchampin/sowasm/issues/4 I tried running the Monaco editor using the ESM import, and it worked without any issue! (the problem I faced in my app was due to a HighlightJS import conflict). The API to manipulate the Monaco editor is quite straightforward, so I went ahead and updated the app:

- Use the Monaco editor for input and output, it works exactly like before, but now uses the Monaco editor instead of textarea
- Enabled automatic language change when the input/output format changes. It switches between xml, json, and sparql (works for every w3c syntax: nt, turtle, quads...)
- Used the solarized-dark theme from https://github.com/brijeshb42/monaco-themes/tree/master/themes
- Changed the layout to use flexbox, center items, and make it responsive: on medium and large screen the input and output editor will be displayed side by side, on small screen they will be displayed on top of each other
- Added the w3c RDF logo as SVG to use as favicon (feel free to change if you have a better idea in mind)

There is still the placeholder in the input editor to implement, I added a comment with a pointer on how to do it

Here is what it looks like with the solarized-dark theme:

![Screenshot from 2023-11-29 11-37-06](https://github.com/pchampin/sowasm/assets/3778439/8cf536c9-9a1e-4ab8-a78f-78e5cc2d6283)

And with the solarized-light theme:

![Screenshot from 2023-11-29 11-39-19](https://github.com/pchampin/sowasm/assets/3778439/75995344-63b8-4182-b9d3-3d4141af64dc)

2023-11-29 12:32 UTC, pchampin requested changes
Thanks a lot for this. 

I wish you had split the different changes (improve HTML+CSS, add Monaco editor) in separates PRs, but now that it is done, I will not ask you to redo the work.

I suggested a few changes, some of them pure linting, but one of them is actually a regressop,: the input editor was previously made readable once the URL had been loaded, and this is not the case anymore.

2023-11-29 12:32 UTC, pchampin commented on demo/script.js
>              input.disabled = false;
```suggestion
            ieditor.updateOptions({readOnly: true});
```

2023-11-29 12:32 UTC, pchampin commented on demo/script.js
> +    const theme = await (await fetch('assets/Solarized-dark.json')).json()
```suggestion
    const theme = await (await fetch('assets/Solarized-dark.json')).json();
```

2023-11-29 12:32 UTC, pchampin commented on demo/script.js
> +        return 'sparql'
```suggestion
        if (format.endsWith('json')) return 'json';
        if (format.endsWith('xml')) return 'xml';
        return 'sparql';
```

2023-11-29 12:32 UTC, pchampin commented on demo/script.js
> +            ieditor.setValue(await resp.text())
```suggestion
            ieditor.setValue(await resp.text());
```

2023-11-29 13:21 UTC, vemonet commented
Sorry, I thought separating it in different commits would be enough, and I needed to have the Monaco editors setup to properly do the work on the CSS display

I also removed some leftovers that were not used anymore

2023-11-30 10:20 UTC, vemonet reviewed
Look good to me, just I am not sure I understand the situation with the input editor being set readonly when using a URL to load the RDF

When I check your original version after loading a URL the editor is still editable. Currently how we implemented in this new version the input editor is set to readonly if a URL is provided

2023-11-30 10:48 UTC, pchampin commented
> Look good to me, just I am not sure I understand the situation with the input editor being set readonly when using a URL to load the RDF
> 
> When I check your original version after loading a URL the editor is still editable. Currently how we implemented in this new version the input editor is set to readonly if a URL is provided

The editor is set to read-only only while the URL is loading. The goal was two-fold
- change the style of the textarea (ligher text) to make it clear that "(loading)" was a message rather than an input
  (but I guess that's moot, I don't think that Monaco changes its style when read-only)
- to prevent the user to type something that would be lost once the content is loaded

2023-11-30 12:38 UTC, vemonet commented
Ok, I fixed it

2023-11-30 16:03 UTC, vemonet commented
I also have the code ready to add inline error highlighting in the editor :) It works perfectly for syntax errors I tried in trig/turtle/nt/nq!

For JSON-LD we get only a position without line, I suspect this is a position after removing newlines and extra spaces, so this might need additional work to get it to work perfectly. That said the built-in JSON validation already helps to pick up all regular JSON errors

Not sure if I should wait for this PR to be merged to create a new one, or if I can directly push to this PR? It's only adding 1 function ~10 lines

2023-12-01 14:18 UTC, pchampin commented
> I also have the code ready to add inline error highlighting in the editor :) It works perfectly for syntax errors I tried in trig/turtle/nt/nq!

nice! :)
 
> For JSON-LD we get only a position without line, I suspect this is a position after removing newlines and extra spaces, so this might need additional work to get it to work perfectly. That said the built-in JSON validation already helps to pick up all regular JSON errors
> 
> Not sure if I should wait for this PR to be merged to create a new one, or if I can directly push to this PR? It's only adding 1 function ~10 lines

I guess it is small enough to include, then

2023-12-01 14:22 UTC, pchampin commented
I thought I had written this comment already, but I must have forgot to press 'Comment'???

There are currently two issues that are really bothering me:

* when pressing 'tab' in the Monaco editor, it... inserts a tab ;
   contrast with the textarea, where 'tab' allows to focus the next element of the page.
   This is important for accessibility.

* the Monaco editor does not emit the 'input' event in the following situations :
  + when you press delete or backspace,
  + when you cut or paste text.
  
  This breaks the good working of the 'automatic' mode.
  
As much as I appreciate and like the work you have been doing, those are really blocking issues for me at this point :-/

2023-12-01 19:53 UTC, vemonet commented
You can still toggle between the default tab behavior and adding tabs by hitting `Ctrl + m`, we could add a small note to let people know. But I guess you would prefer to have the default behavior by default, so I added a fix to enable this (but we cannot use `ctrl+m` to go back to "adding tabs" behavior anymore)

I also updated the listener to use the builtin onInputChange event of the monaco editor, so it properly updates at every change now

2023-12-04 11:49 UTC, merged